-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\decoderN4ByFullMatlabOneFunction\N2decoder.vhd
-- Created: 2017-04-28 00:04:17
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: N2decoder
-- Source Path: decoderN4ByFullMatlabOneFunction/HDL_DUT/N2decoder
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.HDL_DUT_pkg.ALL;

ENTITY N2decoder IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        LLR1                              :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        LRR2                              :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        LLR3                              :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        LLR4                              :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        u1                                :   OUT   std_logic;
        u2                                :   OUT   std_logic;
        u3                                :   OUT   std_logic;
        u4                                :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        soft1                             :   OUT   std_logic_vector(7 DOWNTO 0);  -- int8
        soft2                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        soft3                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        soft4                             :   OUT   std_logic_vector(31 DOWNTO 0)  -- int32
        );
END N2decoder;


ARCHITECTURE rtl OF N2decoder IS

  -- Constants
  CONSTANT nc                             : std_logic_vector(0 TO 3) := 
    ('0', '1', '1', '1');  -- boolean [4]
  CONSTANT nc_0                           : vector_of_signed8(0 TO 99) := 
    (to_signed(16#36#, 8), to_signed(16#21#, 8), to_signed(16#0B#, 8), to_signed(16#3E#, 8), to_signed(16#4E#, 8),
     to_signed(16#2B#, 8), to_signed(16#0A#, 8), to_signed(16#1B#, 8), to_signed(16#10#, 8), to_signed(16#1D#, 8),
     to_signed(16#2D#, 8), to_signed(16#35#, 8), to_signed(16#2E#, 8), to_signed(16#58#, 8), to_signed(16#34#, 8),
     to_signed(16#5F#, 8), to_signed(16#40#, 8), to_signed(16#60#, 8), to_signed(16#19#, 8), to_signed(16#44#, 8),
     to_signed(16#1D#, 8), to_signed(16#44#, 8), to_signed(16#46#, 8), to_signed(16#07#, 8), to_signed(16#1A#, 8),
     to_signed(16#17#, 8), to_signed(16#43#, 8), to_signed(16#55#, 8), to_signed(16#23#, 8), to_signed(16#4F#, 8),
     to_signed(16#44#, 8), to_signed(16#01#, 8), to_signed(16#3D#, 8), to_signed(16#27#, 8), to_signed(16#5C#, 8),
     to_signed(16#01#, 8), to_signed(16#2F#, 8), to_signed(16#2B#, 8), to_signed(16#2F#, 8), to_signed(16#4E#, 8),
     to_signed(16#21#, 8), to_signed(16#4F#, 8), to_signed(16#30#, 8), to_signed(16#04#, 8), to_signed(16#12#, 8),
     to_signed(16#49#, 8), to_signed(16#30#, 8), to_signed(16#10#, 8), to_signed(16#23#, 8), to_signed(16#3D#, 8),
     to_signed(16#14#, 8), to_signed(16#4A#, 8), to_signed(16#19#, 8), to_signed(16#5C#, 8), to_signed(16#1B#, 8),
     to_signed(16#4D#, 8), to_signed(16#13#, 8), to_signed(16#1D#, 8), to_signed(16#0A#, 8), to_signed(16#3A#, 8),
     to_signed(16#45#, 8), to_signed(16#37#, 8), to_signed(16#2B#, 8), to_signed(16#41#, 8), to_signed(16#41#, 8),
     to_signed(16#44#, 8), to_signed(16#40#, 8), to_signed(16#5F#, 8), to_signed(16#15#, 8), to_signed(16#47#, 8),
     to_signed(16#18#, 8), to_signed(16#0C#, 8), to_signed(16#3D#, 8), to_signed(16#2E#, 8), to_signed(16#2E#, 8),
     to_signed(16#43#, 8), to_signed(16#4E#, 8), to_signed(16#24#, 8), to_signed(16#43#, 8), to_signed(16#2A#, 8),
     to_signed(16#55#, 8), to_signed(16#54#, 8), to_signed(16#1A#, 8), to_signed(16#3E#, 8), to_signed(16#3B#, 8),
     to_signed(16#37#, 8), to_signed(16#57#, 8), to_signed(16#1B#, 8), to_signed(16#20#, 8), to_signed(16#0C#, 8),
     to_signed(16#5E#, 8), to_signed(16#41#, 8), to_signed(16#30#, 8), to_signed(16#40#, 8), to_signed(16#37#, 8),
     to_signed(16#41#, 8), to_signed(16#37#, 8), to_signed(16#49#, 8), to_signed(16#35#, 8),
     to_signed(16#64#, 8));  -- int8 [100]

  -- Signals
  SIGNAL LLR1_signed                      : signed(7 DOWNTO 0);  -- int8
  SIGNAL LRR2_signed                      : signed(7 DOWNTO 0);  -- int8
  SIGNAL LLR3_signed                      : signed(7 DOWNTO 0);  -- int8
  SIGNAL LLR4_signed                      : signed(7 DOWNTO 0);  -- int8
  SIGNAL u4_tmp                           : signed(7 DOWNTO 0);  -- int8
  SIGNAL soft1_tmp                        : signed(7 DOWNTO 0);  -- int8
  SIGNAL soft2_tmp                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL soft3_tmp                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL soft4_tmp                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL intArray_not_empty               : std_logic;
  SIGNAL intArray_not_empty_next          : std_logic;

BEGIN
  LLR1_signed <= signed(LLR1);

  LRR2_signed <= signed(LRR2);

  LLR3_signed <= signed(LLR3);

  LLR4_signed <= signed(LLR4);

  N2decoder_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      intArray_not_empty <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        intArray_not_empty <= intArray_not_empty_next;
      END IF;
    END IF;
  END PROCESS N2decoder_1_process;

  N2decoder_1_output : PROCESS (LLR1_signed, LRR2_signed, LLR3_signed, LLR4_signed, intArray_not_empty)
    VARIABLE u11 : std_logic;
    VARIABLE u21 : std_logic;
    VARIABLE u31 : std_logic;
    VARIABLE L21y12 : signed(7 DOWNTO 0);
    VARIABLE L21y34 : signed(7 DOWNTO 0);
    VARIABLE L41y14 : signed(7 DOWNTO 0);
    VARIABLE L42y14u11 : signed(31 DOWNTO 0);
    VARIABLE L22y12u12 : signed(31 DOWNTO 0);
    VARIABLE L22y34u2 : signed(31 DOWNTO 0);
    VARIABLE L43y14u12 : signed(31 DOWNTO 0);
    VARIABLE y : signed(7 DOWNTO 0);
    VARIABLE y_0 : signed(7 DOWNTO 0);
    VARIABLE y_1 : signed(7 DOWNTO 0);
    VARIABLE y_2 : signed(7 DOWNTO 0);
    VARIABLE y_3 : signed(7 DOWNTO 0);
    VARIABLE y_4 : signed(7 DOWNTO 0);
    VARIABLE y_5 : signed(7 DOWNTO 0);
    VARIABLE y_6 : signed(7 DOWNTO 0);
    VARIABLE y_7 : signed(7 DOWNTO 0);
    VARIABLE y_8 : signed(31 DOWNTO 0);
    VARIABLE y_9 : signed(31 DOWNTO 0);
    VARIABLE y_10 : signed(31 DOWNTO 0);
    VARIABLE FZlookup : std_logic_vector(0 TO 3);
    VARIABLE intArray : vector_of_signed8(0 TO 99);
    VARIABLE t_0 : signed(8 DOWNTO 0);
    VARIABLE t_1 : signed(8 DOWNTO 0);
    VARIABLE t_2 : signed(8 DOWNTO 0);
    VARIABLE t_3 : signed(8 DOWNTO 0);
    VARIABLE y_11 : signed(8 DOWNTO 0);
    VARIABLE t_4 : signed(8 DOWNTO 0);
    VARIABLE t_5 : signed(8 DOWNTO 0);
    VARIABLE t_6 : signed(8 DOWNTO 0);
    VARIABLE t_7 : signed(8 DOWNTO 0);
    VARIABLE y_12 : signed(8 DOWNTO 0);
    VARIABLE l21y12_0 : signed(8 DOWNTO 0);
    VARIABLE l21y12_1 : signed(8 DOWNTO 0);
    VARIABLE l21y34_0 : signed(8 DOWNTO 0);
    VARIABLE l21y34_1 : signed(8 DOWNTO 0);
    VARIABLE y_13 : signed(8 DOWNTO 0);
    VARIABLE l21y12_2 : signed(8 DOWNTO 0);
    VARIABLE add_cast : signed(7 DOWNTO 0);
    VARIABLE cast : signed(31 DOWNTO 0);
    VARIABLE cast_0 : signed(31 DOWNTO 0);
    VARIABLE t_8 : signed(8 DOWNTO 0);
    VARIABLE add_cast_0 : signed(7 DOWNTO 0);
    VARIABLE t_9 : signed(8 DOWNTO 0);
    VARIABLE add_cast_1 : signed(7 DOWNTO 0);
    VARIABLE l22y12u12_0 : signed(32 DOWNTO 0);
    VARIABLE l22y12u12_1 : signed(32 DOWNTO 0);
    VARIABLE l22y34u2_0 : signed(32 DOWNTO 0);
    VARIABLE l22y34u2_1 : signed(32 DOWNTO 0);
    VARIABLE y_14 : signed(32 DOWNTO 0);
  BEGIN
    FZlookup := nc;
    intArray := nc_0;
    intArray_not_empty_next <= intArray_not_empty;
    IF ((LLR1_signed > to_signed(16#00000000#, 8)) AND (LRR2_signed > to_signed(16#00000000#, 8))) OR ((LLR1_signed < to_signed(16#00000000#, 8)) AND (LRR2_signed < to_signed(16#00000000#, 8))) THEN 
      IF LLR1_signed < to_signed(16#00000000#, 8) THEN 
        t_1 :=  - (resize(LLR1_signed, 9));
        IF (t_1(8) = '0') AND (t_1(7) /= '0') THEN 
          y_1 := "01111111";
        ELSIF (t_1(8) = '1') AND (t_1(7) /= '1') THEN 
          y_1 := "10000000";
        ELSE 
          y_1 := t_1(7 DOWNTO 0);
        END IF;
      ELSE 
        y_1 := LLR1_signed;
      END IF;
      IF LRR2_signed < to_signed(16#00000000#, 8) THEN 
        t_3 :=  - (resize(LRR2_signed, 9));
        IF (t_3(8) = '0') AND (t_3(7) /= '0') THEN 
          L21y12 := "01111111";
        ELSIF (t_3(8) = '1') AND (t_3(7) /= '1') THEN 
          L21y12 := "10000000";
        ELSE 
          L21y12 := t_3(7 DOWNTO 0);
        END IF;
      ELSE 
        L21y12 := LRR2_signed;
      END IF;
      IF y_1 < L21y12 THEN 
        L21y12 := y_1;
      END IF;
    ELSE 
      IF LLR1_signed < to_signed(16#00000000#, 8) THEN 
        t_0 :=  - (resize(LLR1_signed, 9));
        IF (t_0(8) = '0') AND (t_0(7) /= '0') THEN 
          y := "01111111";
        ELSIF (t_0(8) = '1') AND (t_0(7) /= '1') THEN 
          y := "10000000";
        ELSE 
          y := t_0(7 DOWNTO 0);
        END IF;
      ELSE 
        y := LLR1_signed;
      END IF;
      IF LRR2_signed < to_signed(16#00000000#, 8) THEN 
        t_2 :=  - (resize(LRR2_signed, 9));
        IF (t_2(8) = '0') AND (t_2(7) /= '0') THEN 
          y_0 := "01111111";
        ELSIF (t_2(8) = '1') AND (t_2(7) /= '1') THEN 
          y_0 := "10000000";
        ELSE 
          y_0 := t_2(7 DOWNTO 0);
        END IF;
      ELSE 
        y_0 := LRR2_signed;
      END IF;
      IF y < y_0 THEN 
        y_0 := y;
      END IF;
      y_11 :=  - (resize(y_0, 9));
      IF (y_11(8) = '0') AND (y_11(7) /= '0') THEN 
        L21y12 := "01111111";
      ELSIF (y_11(8) = '1') AND (y_11(7) /= '1') THEN 
        L21y12 := "10000000";
      ELSE 
        L21y12 := y_11(7 DOWNTO 0);
      END IF;
    END IF;
    IF ((LLR3_signed > to_signed(16#00000000#, 8)) AND (LLR4_signed > to_signed(16#00000000#, 8))) OR ((LLR3_signed < to_signed(16#00000000#, 8)) AND (LLR4_signed < to_signed(16#00000000#, 8))) THEN 
      IF LLR3_signed < to_signed(16#00000000#, 8) THEN 
        t_5 :=  - (resize(LLR3_signed, 9));
        IF (t_5(8) = '0') AND (t_5(7) /= '0') THEN 
          y_4 := "01111111";
        ELSIF (t_5(8) = '1') AND (t_5(7) /= '1') THEN 
          y_4 := "10000000";
        ELSE 
          y_4 := t_5(7 DOWNTO 0);
        END IF;
      ELSE 
        y_4 := LLR3_signed;
      END IF;
      IF LLR4_signed < to_signed(16#00000000#, 8) THEN 
        t_7 :=  - (resize(LLR4_signed, 9));
        IF (t_7(8) = '0') AND (t_7(7) /= '0') THEN 
          L21y34 := "01111111";
        ELSIF (t_7(8) = '1') AND (t_7(7) /= '1') THEN 
          L21y34 := "10000000";
        ELSE 
          L21y34 := t_7(7 DOWNTO 0);
        END IF;
      ELSE 
        L21y34 := LLR4_signed;
      END IF;
      IF y_4 < L21y34 THEN 
        L21y34 := y_4;
      END IF;
    ELSE 
      IF LLR3_signed < to_signed(16#00000000#, 8) THEN 
        t_4 :=  - (resize(LLR3_signed, 9));
        IF (t_4(8) = '0') AND (t_4(7) /= '0') THEN 
          y_2 := "01111111";
        ELSIF (t_4(8) = '1') AND (t_4(7) /= '1') THEN 
          y_2 := "10000000";
        ELSE 
          y_2 := t_4(7 DOWNTO 0);
        END IF;
      ELSE 
        y_2 := LLR3_signed;
      END IF;
      IF LLR4_signed < to_signed(16#00000000#, 8) THEN 
        t_6 :=  - (resize(LLR4_signed, 9));
        IF (t_6(8) = '0') AND (t_6(7) /= '0') THEN 
          y_3 := "01111111";
        ELSIF (t_6(8) = '1') AND (t_6(7) /= '1') THEN 
          y_3 := "10000000";
        ELSE 
          y_3 := t_6(7 DOWNTO 0);
        END IF;
      ELSE 
        y_3 := LLR4_signed;
      END IF;
      IF y_2 < y_3 THEN 
        y_3 := y_2;
      END IF;
      y_12 :=  - (resize(y_3, 9));
      IF (y_12(8) = '0') AND (y_12(7) /= '0') THEN 
        L21y34 := "01111111";
      ELSIF (y_12(8) = '1') AND (y_12(7) /= '1') THEN 
        L21y34 := "10000000";
      ELSE 
        L21y34 := y_12(7 DOWNTO 0);
      END IF;
    END IF;
    IF ((L21y12 > to_signed(16#00000000#, 8)) AND (L21y34 > to_signed(16#00000000#, 8))) OR ((L21y12 < to_signed(16#00000000#, 8)) AND (L21y34 < to_signed(16#00000000#, 8))) THEN 
      IF L21y12 < to_signed(16#00000000#, 8) THEN 
        l21y12_1 :=  - (resize(L21y12, 9));
        IF (l21y12_1(8) = '0') AND (l21y12_1(7) /= '0') THEN 
          y_7 := "01111111";
        ELSIF (l21y12_1(8) = '1') AND (l21y12_1(7) /= '1') THEN 
          y_7 := "10000000";
        ELSE 
          y_7 := l21y12_1(7 DOWNTO 0);
        END IF;
      ELSE 
        y_7 := L21y12;
      END IF;
      IF L21y34 < to_signed(16#00000000#, 8) THEN 
        l21y34_1 :=  - (resize(L21y34, 9));
        IF (l21y34_1(8) = '0') AND (l21y34_1(7) /= '0') THEN 
          L41y14 := "01111111";
        ELSIF (l21y34_1(8) = '1') AND (l21y34_1(7) /= '1') THEN 
          L41y14 := "10000000";
        ELSE 
          L41y14 := l21y34_1(7 DOWNTO 0);
        END IF;
      ELSE 
        L41y14 := L21y34;
      END IF;
      IF y_7 < L41y14 THEN 
        L41y14 := y_7;
      END IF;
    ELSE 
      IF L21y12 < to_signed(16#00000000#, 8) THEN 
        l21y12_0 :=  - (resize(L21y12, 9));
        IF (l21y12_0(8) = '0') AND (l21y12_0(7) /= '0') THEN 
          y_5 := "01111111";
        ELSIF (l21y12_0(8) = '1') AND (l21y12_0(7) /= '1') THEN 
          y_5 := "10000000";
        ELSE 
          y_5 := l21y12_0(7 DOWNTO 0);
        END IF;
      ELSE 
        y_5 := L21y12;
      END IF;
      IF L21y34 < to_signed(16#00000000#, 8) THEN 
        l21y34_0 :=  - (resize(L21y34, 9));
        IF (l21y34_0(8) = '0') AND (l21y34_0(7) /= '0') THEN 
          y_6 := "01111111";
        ELSIF (l21y34_0(8) = '1') AND (l21y34_0(7) /= '1') THEN 
          y_6 := "10000000";
        ELSE 
          y_6 := l21y34_0(7 DOWNTO 0);
        END IF;
      ELSE 
        y_6 := L21y34;
      END IF;
      IF y_5 < y_6 THEN 
        y_6 := y_5;
      END IF;
      y_13 :=  - (resize(y_6, 9));
      IF (y_13(8) = '0') AND (y_13(7) /= '0') THEN 
        L41y14 := "01111111";
      ELSIF (y_13(8) = '1') AND (y_13(7) /= '1') THEN 
        L41y14 := "10000000";
      ELSE 
        L41y14 := y_13(7 DOWNTO 0);
      END IF;
    END IF;
    soft1_tmp <= L41y14;
    --FZlookup是冻结比特位置信息，false代表这一位是冻结比特
    IF FZlookup(0) = '1' THEN 
      IF L41y14 > to_signed(16#00000000#, 8) THEN 
        --PCparams.LLR(1) 就是根据最左边的LLR硬裁决
        u11 := '0';
      ELSE 
        u11 := '1';
      END IF;
    ELSE 
      u11 := FZlookup(0);
    END IF;
    IF ( NOT u11) = '1' THEN 
      L42y14u11 := resize(L21y12, 32) + resize(L21y34, 32);
    ELSE 
      l21y12_2 :=  - (resize(L21y12, 9));
      IF (l21y12_2(8) = '0') AND (l21y12_2(7) /= '0') THEN 
        add_cast := "01111111";
      ELSIF (l21y12_2(8) = '1') AND (l21y12_2(7) /= '1') THEN 
        add_cast := "10000000";
      ELSE 
        add_cast := l21y12_2(7 DOWNTO 0);
      END IF;
      L42y14u11 := resize(add_cast, 32) + resize(L21y34, 32);
    END IF;
    soft2_tmp <= L42y14u11;
    --FZlookup是冻结比特位置信息，false代表这一位是冻结比特
    IF FZlookup(1) = '1' THEN 
      IF L42y14u11 > to_signed(16#00000000#, 32) THEN 
        --PCparams.LLR(1) 就是根据最左边的LLR硬裁决
        u21 := '0';
      ELSE 
        u21 := '1';
      END IF;
    ELSE 
      u21 := FZlookup(1);
    END IF;
    --计算u3
    cast := '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & u11;
    cast_0 := '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & u21;
    IF  NOT ((cast XOR cast_0) /= to_signed(16#00000000#, 32)) THEN 
      L22y12u12 := resize(LLR1_signed, 32) + resize(LRR2_signed, 32);
    ELSE 
      t_8 :=  - (resize(LLR1_signed, 9));
      IF (t_8(8) = '0') AND (t_8(7) /= '0') THEN 
        add_cast_0 := "01111111";
      ELSIF (t_8(8) = '1') AND (t_8(7) /= '1') THEN 
        add_cast_0 := "10000000";
      ELSE 
        add_cast_0 := t_8(7 DOWNTO 0);
      END IF;
      L22y12u12 := resize(add_cast_0, 32) + resize(LRR2_signed, 32);
    END IF;
    IF ( NOT u21) = '1' THEN 
      L22y34u2 := resize(LLR3_signed, 32) + resize(LLR4_signed, 32);
    ELSE 
      t_9 :=  - (resize(LLR3_signed, 9));
      IF (t_9(8) = '0') AND (t_9(7) /= '0') THEN 
        add_cast_1 := "01111111";
      ELSIF (t_9(8) = '1') AND (t_9(7) /= '1') THEN 
        add_cast_1 := "10000000";
      ELSE 
        add_cast_1 := t_9(7 DOWNTO 0);
      END IF;
      L22y34u2 := resize(add_cast_1, 32) + resize(LLR4_signed, 32);
    END IF;
    IF ((L22y12u12 > to_signed(16#00000000#, 32)) AND (L22y34u2 > to_signed(16#00000000#, 32))) OR ((L22y12u12 < to_signed(16#00000000#, 32)) AND (L22y34u2 < to_signed(16#00000000#, 32))) THEN 
      IF L22y12u12 < to_signed(16#00000000#, 32) THEN 
        l22y12u12_1 :=  - (resize(L22y12u12, 33));
        y_10 := l22y12u12_1(31 DOWNTO 0);
      ELSE 
        y_10 := L22y12u12;
      END IF;
      IF L22y34u2 < to_signed(16#00000000#, 32) THEN 
        l22y34u2_1 :=  - (resize(L22y34u2, 33));
        L43y14u12 := l22y34u2_1(31 DOWNTO 0);
      ELSE 
        L43y14u12 := L22y34u2;
      END IF;
      IF y_10 < L43y14u12 THEN 
        L43y14u12 := y_10;
      END IF;
    ELSE 
      IF L22y12u12 < to_signed(16#00000000#, 32) THEN 
        l22y12u12_0 :=  - (resize(L22y12u12, 33));
        y_8 := l22y12u12_0(31 DOWNTO 0);
      ELSE 
        y_8 := L22y12u12;
      END IF;
      IF L22y34u2 < to_signed(16#00000000#, 32) THEN 
        l22y34u2_0 :=  - (resize(L22y34u2, 33));
        y_9 := l22y34u2_0(31 DOWNTO 0);
      ELSE 
        y_9 := L22y34u2;
      END IF;
      IF y_8 < y_9 THEN 
        y_9 := y_8;
      END IF;
      y_14 :=  - (resize(y_9, 33));
      L43y14u12 := y_14(31 DOWNTO 0);
    END IF;
    soft3_tmp <= L43y14u12;
    --FZlookup是冻结比特位置信息，false代表这一位是冻结比特
    IF FZlookup(2) = '1' THEN 
      IF L43y14u12 > to_signed(16#00000000#, 32) THEN 
        --PCparams.LLR(1) 就是根据最左边的LLR硬裁决
        u31 := '0';
      ELSE 
        u31 := '1';
      END IF;
    ELSE 
      u31 := FZlookup(2);
    END IF;
    --计算u4
    IF ( NOT u31) = '1' THEN 
      soft4_tmp <= L22y12u12 + L22y34u2;
    ELSE 
      soft4_tmp <= L22y34u2 - L22y12u12;
    END IF;
    -- u4=decide(soft4,4);
    IF ( NOT intArray_not_empty) = '1' THEN 
      intArray_not_empty_next <= '1';
    END IF;
    u4_tmp <= intArray(64);
    u1 <= u11;
    u2 <= u21;
    u3 <= u31;
  END PROCESS N2decoder_1_output;


  u4 <= std_logic_vector(u4_tmp);

  soft1 <= std_logic_vector(soft1_tmp);

  soft2 <= std_logic_vector(soft2_tmp);

  soft3 <= std_logic_vector(soft3_tmp);

  soft4 <= std_logic_vector(soft4_tmp);

END rtl;

