-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\untitled\mealy_fsm_blk.vhd
-- Created: 2017-04-25 15:02:07
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: mealy_fsm_blk
-- Source Path: untitled/mealy_fsm/mealy_fsm_blk
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY mealy_fsm_blk IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        A                                 :   IN    std_logic;
        Z                                 :   OUT   std_logic
        );
END mealy_fsm_blk;


ARCHITECTURE rtl OF mealy_fsm_blk IS

  -- Signals
  SIGNAL mealy_state_reg                  : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL mealy_state_reg_next             : unsigned(1 DOWNTO 0);  -- ufix2

BEGIN
  mealy_fsm_blk_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      mealy_state_reg <= to_unsigned(16#0#, 2);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        mealy_state_reg <= mealy_state_reg_next;
      END IF;
    END IF;
  END PROCESS mealy_fsm_blk_1_process;

  mealy_fsm_blk_1_output : PROCESS (A, mealy_state_reg)
  BEGIN
    mealy_state_reg_next <= mealy_state_reg;
    -- Mealy State Machine
    -- y = f(x,u) : 
    -- all actions are condition actions and 
    -- outputs are function of state and input 
    -- switch to new state based on the value state register
    CASE mealy_state_reg IS
      WHEN "00" =>
        -- value of output 'Z' depends both on state and inputs
        IF A = '1' THEN 
          Z <= '1';
          mealy_state_reg_next <= to_unsigned(16#0#, 2);
        ELSE 
          Z <= '0';
          mealy_state_reg_next <= to_unsigned(16#1#, 2);
        END IF;
      WHEN "01" =>
        IF A = '1' THEN 
          Z <= '0';
          mealy_state_reg_next <= to_unsigned(16#0#, 2);
        ELSE 
          Z <= '1';
          mealy_state_reg_next <= to_unsigned(16#1#, 2);
        END IF;
      WHEN "10" =>
        IF A = '1' THEN 
          Z <= '0';
          mealy_state_reg_next <= to_unsigned(16#1#, 2);
        ELSE 
          Z <= '1';
          mealy_state_reg_next <= to_unsigned(16#2#, 2);
        END IF;
      WHEN "11" =>
        IF A = '1' THEN 
          Z <= '1';
          mealy_state_reg_next <= to_unsigned(16#0#, 2);
        ELSE 
          Z <= '0';
          mealy_state_reg_next <= to_unsigned(16#2#, 2);
        END IF;
      WHEN OTHERS => 
        Z <= '0';
    END CASE;
  END PROCESS mealy_fsm_blk_1_output;


END rtl;

