-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\untitled\mealy_fsm.vhd
-- Created: 2017-04-25 15:02:07
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.2
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.2
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: mealy_fsm
-- Source Path: untitled/mealy_fsm
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY mealy_fsm IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic
        );
END mealy_fsm;


ARCHITECTURE rtl OF mealy_fsm IS

  -- Component Declarations
  COMPONENT mealy_fsm_blk
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          A                               :   IN    std_logic;
          Z                               :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : mealy_fsm_blk
    USE ENTITY work.mealy_fsm_blk(rtl);

  -- Signals
  SIGNAL Z                                : std_logic;

BEGIN
  u_mealy_fsm_blk : mealy_fsm_blk
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              A => In1,
              Z => Z
              );

  ce_out <= clk_enable;

  Out1 <= Z;

END rtl;

