-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\defaultMatlabStateMachine\mealy_fsm_tb.vhd
-- Created: 2017-04-25 15:12:40
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.2
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.2
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: mealy_fsm_tb
-- Source Path: 
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.mealy_fsm_tb_pkg.ALL;

ENTITY mealy_fsm_tb IS
END mealy_fsm_tb;


ARCHITECTURE rtl OF mealy_fsm_tb IS

  -- Component Declarations
  COMPONENT mealy_fsm
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          In1                             :   IN    std_logic;
          ce_out                          :   OUT   std_logic;
          Out1                            :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : mealy_fsm
    USE ENTITY work.mealy_fsm(rtl);

  -- Constants
  CONSTANT In1_table_data                 : std_logic_vector(0 TO 50) := 
    ('0',
     '1',
     '1',
     '1',
     '1',
     '0',
     '1',
     '0',
     '1',
     '1',
     '1',
     '1',
     '0',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '0',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '0',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '0',
     '1',
     '1');  -- boolean [51]
  CONSTANT Out1_expected_table_data       : std_logic_vector(0 TO 50) := 
    ('0',
     '0',
     '1',
     '1',
     '1',
     '0',
     '0',
     '0',
     '0',
     '1',
     '1',
     '1',
     '0',
     '0',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '0',
     '0',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '0',
     '0',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '1',
     '0',
     '0',
     '1');  -- boolean [51]

  -- Signals
  SIGNAL clk                              : std_logic;
  SIGNAL reset                            : std_logic;
  SIGNAL clk_enable                       : std_logic;
  SIGNAL Out1_done                        : std_logic;  -- ufix1
  SIGNAL rdEnb                            : std_logic;
  SIGNAL Out1_done_enb                    : std_logic;  -- ufix1
  SIGNAL Out1_addr                        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Out1_active                      : std_logic;  -- ufix1
  SIGNAL Relational_Operator1_out1_addr   : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Relational_Operator1_out1_active : std_logic;  -- ufix1
  SIGNAL tb_enb_delay                     : std_logic;
  SIGNAL Relational_Operator1_out1_enb    : std_logic;  -- ufix1
  SIGNAL In1_1                            : std_logic;
  SIGNAL rawData_In1                      : std_logic;
  SIGNAL holdData_In1                     : std_logic;
  SIGNAL In1_offset                       : std_logic;
  SIGNAL In1_2                            : std_logic;
  SIGNAL check1_done                      : std_logic;  -- ufix1
  SIGNAL snkDonen                         : std_logic;
  SIGNAL resetn                           : std_logic;
  SIGNAL tb_enb                           : std_logic;
  SIGNAL ce_out                           : std_logic;
  SIGNAL Out1                             : std_logic;
  SIGNAL Out1_enb                         : std_logic;  -- ufix1
  SIGNAL Out1_lastAddr                    : std_logic;  -- ufix1
  SIGNAL Out1_expected_1                  : std_logic;
  SIGNAL Out1_expected_2                  : std_logic;
  SIGNAL Out1_ref                         : std_logic;
  SIGNAL Out1_testFailure                 : std_logic;  -- ufix1

BEGIN
  u_mealy_fsm : mealy_fsm
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => clk_enable,
              In1 => In1_2,
              ce_out => ce_out,
              Out1 => Out1
              );

  Out1_done_enb <= Out1_done AND rdEnb;

  
  Out1_active <= '1' WHEN Out1_addr /= to_unsigned(16#32#, 6) ELSE
      '0';

  
  Relational_Operator1_out1_active <= '1' WHEN Relational_Operator1_out1_addr /= to_unsigned(16#32#, 6) ELSE
      '0';

  Relational_Operator1_out1_enb <= Relational_Operator1_out1_active AND (rdEnb AND tb_enb_delay);

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 50
  RelationalOperator1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Relational_Operator1_out1_addr <= to_unsigned(16#00#, 6);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF Relational_Operator1_out1_enb = '1' THEN
        IF Relational_Operator1_out1_addr = to_unsigned(16#32#, 6) THEN 
          Relational_Operator1_out1_addr <= to_unsigned(16#00#, 6);
        ELSE 
          Relational_Operator1_out1_addr <= Relational_Operator1_out1_addr + to_unsigned(16#01#, 6);
        END IF;
      END IF;
    END IF;
  END PROCESS RelationalOperator1_process;


  -- Data source for In1
  In1_1 <= In1_table_data(to_integer(Relational_Operator1_out1_addr));

  
  rawData_In1 <= '1' WHEN In1_1 /= '0' ELSE
      '0';

  -- holdData reg for Relational_Operator1_out1
  stimuli_Relational_Operator1_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_In1 <= 'X';
    ELSIF clk'event AND clk = '1' THEN
      holdData_In1 <= rawData_In1;
    END IF;
  END PROCESS stimuli_Relational_Operator1_out1_process;

  stimuli_Relational_Operator1_out1_1: PROCESS (rawData_In1, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      In1_offset <= holdData_In1;
    ELSE
      In1_offset <= rawData_In1;
    END IF;
  END PROCESS stimuli_Relational_Operator1_out1_1;

  In1_2 <= In1_offset AFTER 2 ns;

  snkDonen <=  NOT check1_done;

  resetn <=  NOT reset;

  tb_enb <= resetn AND snkDonen;

  -- Delay inside enable generation: register depth 1
  u_enable_delay_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tb_enb_delay <= '0';
    ELSIF clk'event AND clk = '1' THEN
      tb_enb_delay <= tb_enb;
    END IF;
  END PROCESS u_enable_delay_process;

  
  rdEnb <= tb_enb_delay WHEN check1_done = '0' ELSE
      '0';

  clk_enable <= rdEnb AFTER 2 ns;

  reset_gen: PROCESS 
  BEGIN
    reset <= '1';
    WAIT FOR 20 ns;
    WAIT UNTIL clk'event AND clk = '1';
    WAIT FOR 2 ns;
    reset <= '0';
    WAIT;
  END PROCESS reset_gen;

  clk_gen: PROCESS 
  BEGIN
    clk <= '1';
    WAIT FOR 5 ns;
    clk <= '0';
    WAIT FOR 5 ns;
    IF check1_done = '1' THEN
      clk <= '1';
      WAIT FOR 5 ns;
      clk <= '0';
      WAIT FOR 5 ns;
      WAIT;
    END IF;
  END PROCESS clk_gen;

  Out1_enb <= ce_out AND Out1_active;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 50
  c_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Out1_addr <= to_unsigned(16#00#, 6);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF Out1_enb = '1' THEN
        IF Out1_addr = to_unsigned(16#32#, 6) THEN 
          Out1_addr <= to_unsigned(16#00#, 6);
        ELSE 
          Out1_addr <= Out1_addr + to_unsigned(16#01#, 6);
        END IF;
      END IF;
    END IF;
  END PROCESS c_3_process;


  
  Out1_lastAddr <= '1' WHEN Out1_addr >= to_unsigned(16#32#, 6) ELSE
      '0';

  Out1_done <= Out1_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check1_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF Out1_done_enb = '1' THEN
        check1_done <= Out1_done;
      END IF;
    END IF;
  END PROCESS checkDone_1_process;

  -- Data source for Out1_expected
  Out1_expected_1 <= Out1_expected_table_data(to_integer(Out1_addr));

  
  Out1_expected_2 <= '1' WHEN Out1_expected_1 /= '0' ELSE
      '0';

  Out1_ref <= Out1_expected_2;

  Out1_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Out1_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND Out1 /= Out1_ref THEN
        Out1_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in Out1: Expected " & to_hex(Out1_ref) & (" Actual " & to_hex(Out1))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS Out1_checker;

  completed_msg: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF check1_done = '1' THEN
        IF Out1_testFailure = '0' THEN
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (PASSED)**************"
            SEVERITY NOTE;
        ELSE
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (FAILED)**************"
            SEVERITY NOTE;
        END IF;
      END IF;
    END IF;
  END PROCESS completed_msg;

END rtl;

