-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\fByFullMatlab\HDL_DUT.vhd
-- Created: 2017-04-20 13:35:44
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HDL_DUT
-- Source Path: fByFullMatlab/HDL_DUT
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY HDL_DUT IS
  PORT( in1                               :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        in2                               :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        out_rsvd                          :   OUT   std_logic_vector(7 DOWNTO 0)  -- int8
        );
END HDL_DUT;


ARCHITECTURE rtl OF HDL_DUT IS

  -- Component Declarations
  COMPONENT MATLAB_Function
    PORT( in1                             :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          in2                             :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          out_rsvd                        :   OUT   std_logic_vector(7 DOWNTO 0)  -- int8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MATLAB_Function
    USE ENTITY work.MATLAB_Function(rtl);

  -- Signals
  SIGNAL out_tmp                          : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_MATLAB_Function : MATLAB_Function
    PORT MAP( in1 => in1,  -- int8
              in2 => in2,  -- int8
              out_rsvd => out_tmp  -- int8
              );

  out_rsvd <= out_tmp;

END rtl;

