-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\f\HDL_DUT_pkg.vhd
-- Created: 2017-04-20 12:58:25
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE HDL_DUT_pkg IS
  TYPE vector_of_signed8 IS ARRAY (NATURAL RANGE <>) OF signed(7 DOWNTO 0);
END HDL_DUT_pkg;

