-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\encoderN8withDelay\HDL_DUT_pkg.vhd
-- Created: 2017-04-25 14:30:31
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE HDL_DUT_pkg IS
  TYPE T_state_type_is_stateMachine IS (IN_state1, IN_state2);
END HDL_DUT_pkg;

