-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\gm_decoderN4ByFullMatlabOneFunction\gm_decoderN4ByFullMatlabOneFunction.vhd
-- Created: 2017-04-28 16:36:03
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: gm_decoderN4ByFullMatlabOneFunction
-- Source Path: gm_decoderN4ByFullMatlabOneFunction
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY gm_decoderN4ByFullMatlabOneFunction IS
END gm_decoderN4ByFullMatlabOneFunction;


ARCHITECTURE rtl OF gm_decoderN4ByFullMatlabOneFunction IS

  -- Signals
  SIGNAL u1                               : std_logic;
  SIGNAL u2                               : std_logic;
  SIGNAL u3                               : std_logic;
  SIGNAL u4                               : std_logic;
  SIGNAL soft1                            : signed(7 DOWNTO 0);  -- int8
  SIGNAL soft2                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL soft3                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL soft4                            : signed(31 DOWNTO 0);  -- int32

BEGIN
  -- Copyright 2015-2016 The MathWorks, Inc.
  -- 
  -- Add your design targeted for ASIC/FPGA inside HDL_DUT
  -- makehdl('HDL_DUT')
  -- 
  -- Note: This model is configured with 'hdlsetup'


END rtl;

