-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\fByFullMatlab\MATLAB_Function.vhd
-- Created: 2017-04-20 13:35:44
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MATLAB_Function
-- Source Path: fByFullMatlab/HDL_DUT/MATLAB Function
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MATLAB_Function IS
  PORT( in1                               :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        in2                               :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        out_rsvd                          :   OUT   std_logic_vector(7 DOWNTO 0)  -- int8
        );
END MATLAB_Function;


ARCHITECTURE rtl OF MATLAB_Function IS

  -- Signals
  SIGNAL in1_signed                       : signed(7 DOWNTO 0);  -- int8
  SIGNAL in2_signed                       : signed(7 DOWNTO 0);  -- int8
  SIGNAL out_tmp                          : signed(7 DOWNTO 0);  -- int8

BEGIN
  in1_signed <= signed(in1);

  in2_signed <= signed(in2);

  MATLAB_Function_1_output : PROCESS (in1_signed, in2_signed)
    VARIABLE y : signed(7 DOWNTO 0);
    VARIABLE y_0 : signed(7 DOWNTO 0);
    VARIABLE y_1 : signed(7 DOWNTO 0);
    VARIABLE y_2 : signed(7 DOWNTO 0);
    VARIABLE t_0 : signed(8 DOWNTO 0);
    VARIABLE t_1 : signed(8 DOWNTO 0);
    VARIABLE t_2 : signed(8 DOWNTO 0);
    VARIABLE t_3 : signed(8 DOWNTO 0);
    VARIABLE y_3 : signed(8 DOWNTO 0);
  BEGIN
    IF ((in1_signed > to_signed(16#00000000#, 8)) AND (in2_signed > to_signed(16#00000000#, 8))) OR ((in1_signed < to_signed(16#00000000#, 8)) AND (in2_signed < to_signed(16#00000000#, 8))) THEN 
      IF in1_signed < to_signed(16#00000000#, 8) THEN 
        t_1 :=  - (resize(in1_signed, 9));
        IF (t_1(8) = '0') AND (t_1(7) /= '0') THEN 
          y_1 := "01111111";
        ELSIF (t_1(8) = '1') AND (t_1(7) /= '1') THEN 
          y_1 := "10000000";
        ELSE 
          y_1 := t_1(7 DOWNTO 0);
        END IF;
      ELSE 
        y_1 := in1_signed;
      END IF;
      IF in2_signed < to_signed(16#00000000#, 8) THEN 
        t_3 :=  - (resize(in2_signed, 9));
        IF (t_3(8) = '0') AND (t_3(7) /= '0') THEN 
          y_2 := "01111111";
        ELSIF (t_3(8) = '1') AND (t_3(7) /= '1') THEN 
          y_2 := "10000000";
        ELSE 
          y_2 := t_3(7 DOWNTO 0);
        END IF;
      ELSE 
        y_2 := in2_signed;
      END IF;
      IF y_1 < y_2 THEN 
        out_tmp <= y_1;
      ELSE 
        out_tmp <= y_2;
      END IF;
    ELSE 
      IF in1_signed < to_signed(16#00000000#, 8) THEN 
        t_0 :=  - (resize(in1_signed, 9));
        IF (t_0(8) = '0') AND (t_0(7) /= '0') THEN 
          y := "01111111";
        ELSIF (t_0(8) = '1') AND (t_0(7) /= '1') THEN 
          y := "10000000";
        ELSE 
          y := t_0(7 DOWNTO 0);
        END IF;
      ELSE 
        y := in1_signed;
      END IF;
      IF in2_signed < to_signed(16#00000000#, 8) THEN 
        t_2 :=  - (resize(in2_signed, 9));
        IF (t_2(8) = '0') AND (t_2(7) /= '0') THEN 
          y_0 := "01111111";
        ELSIF (t_2(8) = '1') AND (t_2(7) /= '1') THEN 
          y_0 := "10000000";
        ELSE 
          y_0 := t_2(7 DOWNTO 0);
        END IF;
      ELSE 
        y_0 := in2_signed;
      END IF;
      IF y < y_0 THEN 
        y_0 := y;
      END IF;
      y_3 :=  - (resize(y_0, 9));
      IF (y_3(8) = '0') AND (y_3(7) /= '0') THEN 
        out_tmp <= "01111111";
      ELSIF (y_3(8) = '1') AND (y_3(7) /= '1') THEN 
        out_tmp <= "10000000";
      ELSE 
        out_tmp <= y_3(7 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS MATLAB_Function_1_output;


  out_rsvd <= std_logic_vector(out_tmp);

END rtl;

