-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\defaultStateflow\moore_sf_pkg.vhd
-- Created: 2017-04-25 14:39:54
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE moore_sf_pkg IS
  TYPE T_state_type_is_Simple_Moore_Chart IS (IN_COUNTING, IN_IDLE);
END moore_sf_pkg;

