-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\N4\HDL_DUT_tb.vhd
-- Created: 2017-04-20 17:00:56
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HDL_DUT_tb
-- Source Path: 
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_textio.ALL;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
LIBRARY STD;
USE STD.textio.ALL;
LIBRARY work;
USE work.HDL_DUT_pkg.ALL;
USE work.HDL_DUT_tb_pkg.ALL;

ENTITY HDL_DUT_tb IS
END HDL_DUT_tb;


ARCHITECTURE rtl OF HDL_DUT_tb IS

  -- Component Declarations
  COMPONENT HDL_DUT
    PORT( in1                             :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          in2                             :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          in3                             :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          in4                             :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
          out_rsvd                        :   OUT   std_logic;
          out1                            :   OUT   std_logic;
          out2                            :   OUT   std_logic;
          out3                            :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : HDL_DUT
    USE ENTITY work.HDL_DUT(rtl);

  -- Signals
  SIGNAL clk                              : std_logic;
  SIGNAL reset                            : std_logic;
  SIGNAL enb                              : std_logic;
  SIGNAL out3_done                        : std_logic;  -- ufix1
  SIGNAL rdEnb                            : std_logic;
  SIGNAL out3_done_enb                    : std_logic;  -- ufix1
  SIGNAL out_rsvd_addr                    : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL out3_lastAddr                    : std_logic;  -- ufix1
  SIGNAL resetn                           : std_logic;
  SIGNAL check4_done                      : std_logic;  -- ufix1
  SIGNAL out2_done                        : std_logic;  -- ufix1
  SIGNAL out2_done_enb                    : std_logic;  -- ufix1
  SIGNAL out2_lastAddr                    : std_logic;  -- ufix1
  SIGNAL check3_done                      : std_logic;  -- ufix1
  SIGNAL out1_done                        : std_logic;  -- ufix1
  SIGNAL out1_done_enb                    : std_logic;  -- ufix1
  SIGNAL out1_lastAddr                    : std_logic;  -- ufix1
  SIGNAL check2_done                      : std_logic;  -- ufix1
  SIGNAL out_rsvd_done                    : std_logic;  -- ufix1
  SIGNAL out_rsvd_done_enb                : std_logic;  -- ufix1
  SIGNAL out_rsvd_active                  : std_logic;  -- ufix1
  SIGNAL snkDone                          : std_logic;
  SIGNAL snkDonen                         : std_logic;
  SIGNAL tb_enb                           : std_logic;
  SIGNAL tb_enb_delay                     : std_logic;
  SIGNAL ce_out                           : std_logic;
  SIGNAL out_rsvd_enb                     : std_logic;  -- ufix1
  SIGNAL out_rsvd_lastAddr                : std_logic;  -- ufix1
  SIGNAL check1_done                      : std_logic;  -- ufix1
  SIGNAL rawData_in1                      : signed(7 DOWNTO 0);  -- int8
  SIGNAL holdData_in1                     : signed(7 DOWNTO 0);  -- int8
  SIGNAL rawData_in2                      : signed(7 DOWNTO 0);  -- int8
  SIGNAL holdData_in2                     : signed(7 DOWNTO 0);  -- int8
  SIGNAL rawData_in3                      : signed(7 DOWNTO 0);  -- int8
  SIGNAL holdData_in3                     : signed(7 DOWNTO 0);  -- int8
  SIGNAL rawData_in4                      : signed(7 DOWNTO 0);  -- int8
  SIGNAL holdData_in4                     : signed(7 DOWNTO 0);  -- int8
  SIGNAL in1_offset                       : signed(7 DOWNTO 0);  -- int8
  SIGNAL in1_1                            : signed(7 DOWNTO 0);  -- int8
  SIGNAL in1_2                            : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL in2_offset                       : signed(7 DOWNTO 0);  -- int8
  SIGNAL in2_1                            : signed(7 DOWNTO 0);  -- int8
  SIGNAL in2_2                            : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL in3_offset                       : signed(7 DOWNTO 0);  -- int8
  SIGNAL in3_1                            : signed(7 DOWNTO 0);  -- int8
  SIGNAL in3_2                            : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL in4_offset                       : signed(7 DOWNTO 0);  -- int8
  SIGNAL in4_1                            : signed(7 DOWNTO 0);  -- int8
  SIGNAL in4_2                            : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL out_rsvd                         : std_logic;
  SIGNAL out1                             : std_logic;
  SIGNAL out2                             : std_logic;
  SIGNAL out3                             : std_logic;
  SIGNAL out_rsvd_expected_1              : std_logic;
  SIGNAL out_rsvd_ref                     : std_logic;
  SIGNAL out_rsvd_testFailure             : std_logic;  -- ufix1
  SIGNAL out1_expected_1                  : std_logic;
  SIGNAL out1_ref                         : std_logic;
  SIGNAL out1_testFailure                 : std_logic;  -- ufix1
  SIGNAL out2_expected_1                  : std_logic;
  SIGNAL out2_ref                         : std_logic;
  SIGNAL out2_testFailure                 : std_logic;  -- ufix1
  SIGNAL out3_expected_1                  : std_logic;
  SIGNAL out3_ref                         : std_logic;
  SIGNAL out3_testFailure                 : std_logic;  -- ufix1
  SIGNAL testFailure                      : std_logic;  -- ufix1

BEGIN
  u_HDL_DUT : HDL_DUT
    PORT MAP( in1 => in1_2,  -- int8
              in2 => in2_2,  -- int8
              in3 => in3_2,  -- int8
              in4 => in4_2,  -- int8
              out_rsvd => out_rsvd,
              out1 => out1,
              out2 => out2,
              out3 => out3
              );

  out3_done_enb <= out3_done AND rdEnb;

  
  out3_lastAddr <= '1' WHEN out_rsvd_addr >= to_unsigned(16#32#, 6) ELSE
      '0';

  out3_done <= out3_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_4_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check4_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF out3_done_enb = '1' THEN
        check4_done <= out3_done;
      END IF;
    END IF;
  END PROCESS checkDone_4_process;

  out2_done_enb <= out2_done AND rdEnb;

  
  out2_lastAddr <= '1' WHEN out_rsvd_addr >= to_unsigned(16#32#, 6) ELSE
      '0';

  out2_done <= out2_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_3_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check3_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF out2_done_enb = '1' THEN
        check3_done <= out2_done;
      END IF;
    END IF;
  END PROCESS checkDone_3_process;

  out1_done_enb <= out1_done AND rdEnb;

  
  out1_lastAddr <= '1' WHEN out_rsvd_addr >= to_unsigned(16#32#, 6) ELSE
      '0';

  out1_done <= out1_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_2_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check2_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF out1_done_enb = '1' THEN
        check2_done <= out1_done;
      END IF;
    END IF;
  END PROCESS checkDone_2_process;

  out_rsvd_done_enb <= out_rsvd_done AND rdEnb;

  
  out_rsvd_active <= '1' WHEN out_rsvd_addr /= to_unsigned(16#32#, 6) ELSE
      '0';

  enb <= rdEnb AFTER 2 ns;

  snkDonen <=  NOT snkDone;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 50
  clk_gen: PROCESS 
  BEGIN
    clk <= '1';
    WAIT FOR 5 ns;
    clk <= '0';
    WAIT FOR 5 ns;
    IF snkDone = '1' THEN
      clk <= '1';
      WAIT FOR 5 ns;
      clk <= '0';
      WAIT FOR 5 ns;
      WAIT;
    END IF;
  END PROCESS clk_gen;

  reset_gen: PROCESS 
  BEGIN
    reset <= '1';
    WAIT FOR 20 ns;
    WAIT UNTIL clk'event AND clk = '1';
    WAIT FOR 2 ns;
    reset <= '0';
    WAIT;
  END PROCESS reset_gen;

  resetn <=  NOT reset;

  tb_enb <= resetn AND snkDonen;

  -- Delay inside enable generation: register depth 1
  u_enable_delay_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tb_enb_delay <= '0';
    ELSIF clk'event AND clk = '1' THEN
      tb_enb_delay <= tb_enb;
    END IF;
  END PROCESS u_enable_delay_process;

  
  rdEnb <= tb_enb_delay WHEN snkDone = '0' ELSE
      '0';

  ce_out <= enb AND (rdEnb AND tb_enb_delay);

  out_rsvd_enb <= ce_out AND out_rsvd_active;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 50
  c_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out_rsvd_addr <= to_unsigned(16#00#, 6);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF out_rsvd_enb = '1' THEN
        IF out_rsvd_addr = to_unsigned(16#32#, 6) THEN 
          out_rsvd_addr <= to_unsigned(16#00#, 6);
        ELSE 
          out_rsvd_addr <= out_rsvd_addr + to_unsigned(16#01#, 6);
        END IF;
      END IF;
    END IF;
  END PROCESS c_3_process;


  
  out_rsvd_lastAddr <= '1' WHEN out_rsvd_addr >= to_unsigned(16#32#, 6) ELSE
      '0';

  out_rsvd_done <= out_rsvd_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check1_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF out_rsvd_done_enb = '1' THEN
        check1_done <= out_rsvd_done;
      END IF;
    END IF;
  END PROCESS checkDone_1_process;

  snkDone <= check4_done AND (check3_done AND (check1_done AND check2_done));

  -- Data source for in1
  rawData_in1 <= to_signed(-16#2C#, 8);

  -- holdData reg for Constant_out1
  stimuli_Constant_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_in1 <= (OTHERS => 'X');
    ELSIF clk'event AND clk = '1' THEN
      holdData_in1 <= rawData_in1;
    END IF;
  END PROCESS stimuli_Constant_out1_process;

  -- Data source for in2
  rawData_in2 <= to_signed(-16#40#, 8);

  -- holdData reg for Constant1_out1
  stimuli_Constant1_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_in2 <= (OTHERS => 'X');
    ELSIF clk'event AND clk = '1' THEN
      holdData_in2 <= rawData_in2;
    END IF;
  END PROCESS stimuli_Constant1_out1_process;

  -- Data source for in3
  rawData_in3 <= to_signed(-16#14#, 8);

  -- holdData reg for Constant2_out1
  stimuli_Constant2_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_in3 <= (OTHERS => 'X');
    ELSIF clk'event AND clk = '1' THEN
      holdData_in3 <= rawData_in3;
    END IF;
  END PROCESS stimuli_Constant2_out1_process;

  -- Data source for in4
  rawData_in4 <= to_signed(16#30#, 8);

  -- holdData reg for Constant3_out1
  stimuli_Constant3_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_in4 <= (OTHERS => 'X');
    ELSIF clk'event AND clk = '1' THEN
      holdData_in4 <= rawData_in4;
    END IF;
  END PROCESS stimuli_Constant3_out1_process;

  stimuli_Constant_out1_1: PROCESS (rawData_in1, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      in1_offset <= holdData_in1;
    ELSE
      in1_offset <= rawData_in1;
    END IF;
  END PROCESS stimuli_Constant_out1_1;

  in1_1 <= in1_offset AFTER 2 ns;

  in1_2 <= std_logic_vector(in1_1);

  stimuli_Constant1_out1_1: PROCESS (rawData_in2, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      in2_offset <= holdData_in2;
    ELSE
      in2_offset <= rawData_in2;
    END IF;
  END PROCESS stimuli_Constant1_out1_1;

  in2_1 <= in2_offset AFTER 2 ns;

  in2_2 <= std_logic_vector(in2_1);

  stimuli_Constant2_out1_1: PROCESS (rawData_in3, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      in3_offset <= holdData_in3;
    ELSE
      in3_offset <= rawData_in3;
    END IF;
  END PROCESS stimuli_Constant2_out1_1;

  in3_1 <= in3_offset AFTER 2 ns;

  in3_2 <= std_logic_vector(in3_1);

  stimuli_Constant3_out1_1: PROCESS (rawData_in4, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      in4_offset <= holdData_in4;
    ELSE
      in4_offset <= rawData_in4;
    END IF;
  END PROCESS stimuli_Constant3_out1_1;

  in4_1 <= in4_offset AFTER 2 ns;

  in4_2 <= std_logic_vector(in4_1);

  -- Data source for out_rsvd_expected
  out_rsvd_expected_1 <= '1';

  out_rsvd_ref <= out_rsvd_expected_1;

  out_rsvd_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out_rsvd_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND out_rsvd /= out_rsvd_ref THEN
        out_rsvd_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in out_rsvd: Expected " & to_hex(out_rsvd_ref) & (" Actual " & to_hex(out_rsvd))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS out_rsvd_checker;

  -- Data source for out1_expected
  out1_expected_1 <= '1';

  out1_ref <= out1_expected_1;

  out1_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out1_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND out1 /= out1_ref THEN
        out1_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in out1: Expected " & to_hex(out1_ref) & (" Actual " & to_hex(out1))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS out1_checker;

  -- Data source for out2_expected
  out2_expected_1 <= '1';

  out2_ref <= out2_expected_1;

  out2_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out2_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND out2 /= out2_ref THEN
        out2_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in out2: Expected " & to_hex(out2_ref) & (" Actual " & to_hex(out2))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS out2_checker;

  -- Data source for out3_expected
  out3_expected_1 <= '0';

  out3_ref <= out3_expected_1;

  out3_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out3_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND out3 /= out3_ref THEN
        out3_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in out3: Expected " & to_hex(out3_ref) & (" Actual " & to_hex(out3))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS out3_checker;

  testFailure <= out3_testFailure OR (out2_testFailure OR (out_rsvd_testFailure OR out1_testFailure));

  completed_msg: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF snkDone = '1' THEN
        IF testFailure = '0' THEN
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (PASSED)**************"
            SEVERITY NOTE;
        ELSE
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (FAILED)**************"
            SEVERITY NOTE;
        END IF;
      END IF;
    END IF;
  END PROCESS completed_msg;

END rtl;

