-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\encoderN8\HDL_DUT_tb.vhd
-- Created: 2017-04-21 23:57:35
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HDL_DUT_tb
-- Source Path: 
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.HDL_DUT_tb_pkg.ALL;

ENTITY HDL_DUT_tb IS
END HDL_DUT_tb;


ARCHITECTURE rtl OF HDL_DUT_tb IS

  -- Component Declarations
  COMPONENT HDL_DUT
    PORT( in1                             :   IN    std_logic;
          in2                             :   IN    std_logic;
          in3                             :   IN    std_logic;
          in4                             :   IN    std_logic;
          in5                             :   IN    std_logic;
          in6                             :   IN    std_logic;
          in7                             :   IN    std_logic;
          in8                             :   IN    std_logic;
          out1                            :   OUT   std_logic;
          out2                            :   OUT   std_logic;
          out3                            :   OUT   std_logic;
          out4                            :   OUT   std_logic;
          out5                            :   OUT   std_logic;
          out6                            :   OUT   std_logic;
          out7                            :   OUT   std_logic;
          out8                            :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : HDL_DUT
    USE ENTITY work.HDL_DUT(rtl);

  -- Constants
  CONSTANT in4_table_data                 : std_logic_vector(0 TO 50) := 
    ('0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0');  -- boolean [51]
  CONSTANT out1_expected_table_data       : std_logic_vector(0 TO 50) := 
    ('1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1');  -- boolean [51]
  CONSTANT in4_table_data_2               : std_logic_vector(0 TO 50) := 
    ('0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0');  -- boolean [51]
  CONSTANT in4_table_data_4               : std_logic_vector(0 TO 50) := 
    ('0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0');  -- boolean [51]
  CONSTANT out1_expected_table_data_2     : std_logic_vector(0 TO 50) := 
    ('1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1',
     '0',
     '1');  -- boolean [51]

  -- Signals
  SIGNAL clk                              : std_logic;
  SIGNAL reset                            : std_logic;
  SIGNAL enb                              : std_logic;
  SIGNAL out8_done                        : std_logic;  -- ufix1
  SIGNAL rdEnb                            : std_logic;
  SIGNAL out8_done_enb                    : std_logic;  -- ufix1
  SIGNAL out1_addr                        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL out8_lastAddr                    : std_logic;  -- ufix1
  SIGNAL resetn                           : std_logic;
  SIGNAL check8_done                      : std_logic;  -- ufix1
  SIGNAL out7_done                        : std_logic;  -- ufix1
  SIGNAL out7_done_enb                    : std_logic;  -- ufix1
  SIGNAL out7_lastAddr                    : std_logic;  -- ufix1
  SIGNAL check7_done                      : std_logic;  -- ufix1
  SIGNAL out6_done                        : std_logic;  -- ufix1
  SIGNAL out6_done_enb                    : std_logic;  -- ufix1
  SIGNAL out6_lastAddr                    : std_logic;  -- ufix1
  SIGNAL check6_done                      : std_logic;  -- ufix1
  SIGNAL out5_done                        : std_logic;  -- ufix1
  SIGNAL out5_done_enb                    : std_logic;  -- ufix1
  SIGNAL out5_lastAddr                    : std_logic;  -- ufix1
  SIGNAL check5_done                      : std_logic;  -- ufix1
  SIGNAL out4_done                        : std_logic;  -- ufix1
  SIGNAL out4_done_enb                    : std_logic;  -- ufix1
  SIGNAL out4_lastAddr                    : std_logic;  -- ufix1
  SIGNAL check4_done                      : std_logic;  -- ufix1
  SIGNAL out3_done                        : std_logic;  -- ufix1
  SIGNAL out3_done_enb                    : std_logic;  -- ufix1
  SIGNAL out3_lastAddr                    : std_logic;  -- ufix1
  SIGNAL check3_done                      : std_logic;  -- ufix1
  SIGNAL out2_done                        : std_logic;  -- ufix1
  SIGNAL out2_done_enb                    : std_logic;  -- ufix1
  SIGNAL out2_lastAddr                    : std_logic;  -- ufix1
  SIGNAL check2_done                      : std_logic;  -- ufix1
  SIGNAL out1_done                        : std_logic;  -- ufix1
  SIGNAL out1_done_enb                    : std_logic;  -- ufix1
  SIGNAL out1_active                      : std_logic;  -- ufix1
  SIGNAL snkDone                          : std_logic;
  SIGNAL snkDonen                         : std_logic;
  SIGNAL tb_enb                           : std_logic;
  SIGNAL tb_enb_delay                     : std_logic;
  SIGNAL ce_out                           : std_logic;
  SIGNAL out1_enb                         : std_logic;  -- ufix1
  SIGNAL out1_lastAddr                    : std_logic;  -- ufix1
  SIGNAL check1_done                      : std_logic;  -- ufix1
  SIGNAL rawData_in1                      : std_logic;
  SIGNAL holdData_in1                     : std_logic;
  SIGNAL rawData_in2                      : std_logic;
  SIGNAL holdData_in2                     : std_logic;
  SIGNAL rawData_in3                      : std_logic;
  SIGNAL holdData_in3                     : std_logic;
  SIGNAL Constant_out1_addr               : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Constant_out1_active             : std_logic;  -- ufix1
  SIGNAL Constant_out1_enb                : std_logic;  -- ufix1
  SIGNAL in4_1                            : std_logic;
  SIGNAL rawData_in4                      : std_logic;
  SIGNAL holdData_in4                     : std_logic;
  SIGNAL rawData_in5                      : std_logic;
  SIGNAL holdData_in5                     : std_logic;
  SIGNAL rawData_in6                      : std_logic;
  SIGNAL holdData_in6                     : std_logic;
  SIGNAL rawData_in7                      : std_logic;
  SIGNAL holdData_in7                     : std_logic;
  SIGNAL rawData_in8                      : std_logic;
  SIGNAL holdData_in8                     : std_logic;
  SIGNAL in1_offset                       : std_logic;
  SIGNAL in1_1                            : std_logic;
  SIGNAL in2_offset                       : std_logic;
  SIGNAL in2_1                            : std_logic;
  SIGNAL in3_offset                       : std_logic;
  SIGNAL in3_1                            : std_logic;
  SIGNAL in4_offset                       : std_logic;
  SIGNAL in4_2                            : std_logic;
  SIGNAL in5_offset                       : std_logic;
  SIGNAL in5_1                            : std_logic;
  SIGNAL in6_offset                       : std_logic;
  SIGNAL in6_1                            : std_logic;
  SIGNAL in7_offset                       : std_logic;
  SIGNAL in7_1                            : std_logic;
  SIGNAL in8_offset                       : std_logic;
  SIGNAL in8_1                            : std_logic;
  SIGNAL out1                             : std_logic;
  SIGNAL out2                             : std_logic;
  SIGNAL out3                             : std_logic;
  SIGNAL out4                             : std_logic;
  SIGNAL out5                             : std_logic;
  SIGNAL out6                             : std_logic;
  SIGNAL out7                             : std_logic;
  SIGNAL out8                             : std_logic;
  SIGNAL out1_expected_1                  : std_logic;
  SIGNAL out1_expected_2                  : std_logic;
  SIGNAL out1_ref                         : std_logic;
  SIGNAL out1_testFailure                 : std_logic;  -- ufix1
  SIGNAL out2_expected_1                  : std_logic;
  SIGNAL out2_expected_2                  : std_logic;
  SIGNAL out2_ref                         : std_logic;
  SIGNAL out2_testFailure                 : std_logic;  -- ufix1
  SIGNAL out3_expected_1                  : std_logic;
  SIGNAL out3_expected_2                  : std_logic;
  SIGNAL out3_ref                         : std_logic;
  SIGNAL out3_testFailure                 : std_logic;  -- ufix1
  SIGNAL out4_expected_1                  : std_logic;
  SIGNAL out4_expected_2                  : std_logic;
  SIGNAL out4_ref                         : std_logic;
  SIGNAL out4_testFailure                 : std_logic;  -- ufix1
  SIGNAL out5_expected_1                  : std_logic;
  SIGNAL out5_ref                         : std_logic;
  SIGNAL out5_testFailure                 : std_logic;  -- ufix1
  SIGNAL out6_expected_1                  : std_logic;
  SIGNAL out6_ref                         : std_logic;
  SIGNAL out6_testFailure                 : std_logic;  -- ufix1
  SIGNAL out7_expected_1                  : std_logic;
  SIGNAL out7_ref                         : std_logic;
  SIGNAL out7_testFailure                 : std_logic;  -- ufix1
  SIGNAL out8_expected_1                  : std_logic;
  SIGNAL out8_ref                         : std_logic;
  SIGNAL out8_testFailure                 : std_logic;  -- ufix1
  SIGNAL testFailure                      : std_logic;  -- ufix1

BEGIN
  u_HDL_DUT : HDL_DUT
    PORT MAP( in1 => in1_1,
              in2 => in2_1,
              in3 => in3_1,
              in4 => in4_2,
              in5 => in5_1,
              in6 => in6_1,
              in7 => in7_1,
              in8 => in8_1,
              out1 => out1,
              out2 => out2,
              out3 => out3,
              out4 => out4,
              out5 => out5,
              out6 => out6,
              out7 => out7,
              out8 => out8
              );

  out8_done_enb <= out8_done AND rdEnb;

  
  out8_lastAddr <= '1' WHEN out1_addr >= to_unsigned(16#32#, 6) ELSE
      '0';

  out8_done <= out8_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_8_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check8_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF out8_done_enb = '1' THEN
        check8_done <= out8_done;
      END IF;
    END IF;
  END PROCESS checkDone_8_process;

  out7_done_enb <= out7_done AND rdEnb;

  
  out7_lastAddr <= '1' WHEN out1_addr >= to_unsigned(16#32#, 6) ELSE
      '0';

  out7_done <= out7_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_7_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check7_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF out7_done_enb = '1' THEN
        check7_done <= out7_done;
      END IF;
    END IF;
  END PROCESS checkDone_7_process;

  out6_done_enb <= out6_done AND rdEnb;

  
  out6_lastAddr <= '1' WHEN out1_addr >= to_unsigned(16#32#, 6) ELSE
      '0';

  out6_done <= out6_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_6_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check6_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF out6_done_enb = '1' THEN
        check6_done <= out6_done;
      END IF;
    END IF;
  END PROCESS checkDone_6_process;

  out5_done_enb <= out5_done AND rdEnb;

  
  out5_lastAddr <= '1' WHEN out1_addr >= to_unsigned(16#32#, 6) ELSE
      '0';

  out5_done <= out5_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_5_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check5_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF out5_done_enb = '1' THEN
        check5_done <= out5_done;
      END IF;
    END IF;
  END PROCESS checkDone_5_process;

  out4_done_enb <= out4_done AND rdEnb;

  
  out4_lastAddr <= '1' WHEN out1_addr >= to_unsigned(16#32#, 6) ELSE
      '0';

  out4_done <= out4_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_4_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check4_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF out4_done_enb = '1' THEN
        check4_done <= out4_done;
      END IF;
    END IF;
  END PROCESS checkDone_4_process;

  out3_done_enb <= out3_done AND rdEnb;

  
  out3_lastAddr <= '1' WHEN out1_addr >= to_unsigned(16#32#, 6) ELSE
      '0';

  out3_done <= out3_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_3_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check3_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF out3_done_enb = '1' THEN
        check3_done <= out3_done;
      END IF;
    END IF;
  END PROCESS checkDone_3_process;

  out2_done_enb <= out2_done AND rdEnb;

  
  out2_lastAddr <= '1' WHEN out1_addr >= to_unsigned(16#32#, 6) ELSE
      '0';

  out2_done <= out2_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_2_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check2_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF out2_done_enb = '1' THEN
        check2_done <= out2_done;
      END IF;
    END IF;
  END PROCESS checkDone_2_process;

  out1_done_enb <= out1_done AND rdEnb;

  
  out1_active <= '1' WHEN out1_addr /= to_unsigned(16#32#, 6) ELSE
      '0';

  enb <= rdEnb AFTER 2 ns;

  snkDonen <=  NOT snkDone;

  clk_gen: PROCESS 
  BEGIN
    clk <= '1';
    WAIT FOR 5 ns;
    clk <= '0';
    WAIT FOR 5 ns;
    IF snkDone = '1' THEN
      clk <= '1';
      WAIT FOR 5 ns;
      clk <= '0';
      WAIT FOR 5 ns;
      WAIT;
    END IF;
  END PROCESS clk_gen;

  reset_gen: PROCESS 
  BEGIN
    reset <= '1';
    WAIT FOR 20 ns;
    WAIT UNTIL clk'event AND clk = '1';
    WAIT FOR 2 ns;
    reset <= '0';
    WAIT;
  END PROCESS reset_gen;

  resetn <=  NOT reset;

  tb_enb <= resetn AND snkDonen;

  -- Delay inside enable generation: register depth 1
  u_enable_delay_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tb_enb_delay <= '0';
    ELSIF clk'event AND clk = '1' THEN
      tb_enb_delay <= tb_enb;
    END IF;
  END PROCESS u_enable_delay_process;

  
  rdEnb <= tb_enb_delay WHEN snkDone = '0' ELSE
      '0';

  ce_out <= enb AND (rdEnb AND tb_enb_delay);

  out1_enb <= ce_out AND out1_active;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 50
  c_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out1_addr <= to_unsigned(16#00#, 6);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF out1_enb = '1' THEN
        IF out1_addr = to_unsigned(16#32#, 6) THEN 
          out1_addr <= to_unsigned(16#00#, 6);
        ELSE 
          out1_addr <= out1_addr + to_unsigned(16#01#, 6);
        END IF;
      END IF;
    END IF;
  END PROCESS c_3_process;


  
  out1_lastAddr <= '1' WHEN out1_addr >= to_unsigned(16#32#, 6) ELSE
      '0';

  out1_done <= out1_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check1_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF out1_done_enb = '1' THEN
        check1_done <= out1_done;
      END IF;
    END IF;
  END PROCESS checkDone_1_process;

  snkDone <= check8_done AND (check7_done AND (check6_done AND (check5_done AND (check4_done AND (check3_done AND (check1_done AND check2_done))))));

  -- Data source for in1
  rawData_in1 <= '0';

  -- holdData reg for Constant_out1
  stimuli_Constant_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_in1 <= 'X';
    ELSIF clk'event AND clk = '1' THEN
      holdData_in1 <= rawData_in1;
    END IF;
  END PROCESS stimuli_Constant_out1_process;

  -- Data source for in2
  rawData_in2 <= '0';

  -- holdData reg for Constant1_out1
  stimuli_Constant1_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_in2 <= 'X';
    ELSIF clk'event AND clk = '1' THEN
      holdData_in2 <= rawData_in2;
    END IF;
  END PROCESS stimuli_Constant1_out1_process;

  -- Data source for in3
  rawData_in3 <= '0';

  -- holdData reg for Constant2_out1
  stimuli_Constant2_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_in3 <= 'X';
    ELSIF clk'event AND clk = '1' THEN
      holdData_in3 <= rawData_in3;
    END IF;
  END PROCESS stimuli_Constant2_out1_process;

  
  Constant_out1_active <= '1' WHEN Constant_out1_addr /= to_unsigned(16#32#, 6) ELSE
      '0';

  Constant_out1_enb <= Constant_out1_active AND (rdEnb AND tb_enb_delay);

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 50
  Constant_rsvd_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Constant_out1_addr <= to_unsigned(16#00#, 6);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF Constant_out1_enb = '1' THEN
        IF Constant_out1_addr = to_unsigned(16#32#, 6) THEN 
          Constant_out1_addr <= to_unsigned(16#00#, 6);
        ELSE 
          Constant_out1_addr <= Constant_out1_addr + to_unsigned(16#01#, 6);
        END IF;
      END IF;
    END IF;
  END PROCESS Constant_rsvd_process;


  -- Data source for in4
  in4_1 <= in4_table_data(to_integer(Constant_out1_addr));

  
  rawData_in4 <= '1' WHEN in4_1 /= '0' ELSE
      '0';

  -- holdData reg for Compare_To_Zero_out1
  stimuli_Compare_To_Zero_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_in4 <= 'X';
    ELSIF clk'event AND clk = '1' THEN
      holdData_in4 <= rawData_in4;
    END IF;
  END PROCESS stimuli_Compare_To_Zero_out1_process;

  -- Data source for in5
  rawData_in5 <= '0';

  -- holdData reg for Constant4_out1
  stimuli_Constant4_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_in5 <= 'X';
    ELSIF clk'event AND clk = '1' THEN
      holdData_in5 <= rawData_in5;
    END IF;
  END PROCESS stimuli_Constant4_out1_process;

  -- Data source for in6
  rawData_in6 <= '1';

  -- holdData reg for Constant5_out1
  stimuli_Constant5_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_in6 <= 'X';
    ELSIF clk'event AND clk = '1' THEN
      holdData_in6 <= rawData_in6;
    END IF;
  END PROCESS stimuli_Constant5_out1_process;

  -- Data source for in7
  rawData_in7 <= '1';

  -- holdData reg for Constant6_out1
  stimuli_Constant6_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_in7 <= 'X';
    ELSIF clk'event AND clk = '1' THEN
      holdData_in7 <= rawData_in7;
    END IF;
  END PROCESS stimuli_Constant6_out1_process;

  -- Data source for in8
  rawData_in8 <= '1';

  -- holdData reg for Constant7_out1
  stimuli_Constant7_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_in8 <= 'X';
    ELSIF clk'event AND clk = '1' THEN
      holdData_in8 <= rawData_in8;
    END IF;
  END PROCESS stimuli_Constant7_out1_process;

  stimuli_Constant_out1_1: PROCESS (rawData_in1, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      in1_offset <= holdData_in1;
    ELSE
      in1_offset <= rawData_in1;
    END IF;
  END PROCESS stimuli_Constant_out1_1;

  in1_1 <= in1_offset AFTER 2 ns;

  stimuli_Constant1_out1_1: PROCESS (rawData_in2, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      in2_offset <= holdData_in2;
    ELSE
      in2_offset <= rawData_in2;
    END IF;
  END PROCESS stimuli_Constant1_out1_1;

  in2_1 <= in2_offset AFTER 2 ns;

  stimuli_Constant2_out1_1: PROCESS (rawData_in3, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      in3_offset <= holdData_in3;
    ELSE
      in3_offset <= rawData_in3;
    END IF;
  END PROCESS stimuli_Constant2_out1_1;

  in3_1 <= in3_offset AFTER 2 ns;

  stimuli_Compare_To_Zero_out1_1: PROCESS (rawData_in4, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      in4_offset <= holdData_in4;
    ELSE
      in4_offset <= rawData_in4;
    END IF;
  END PROCESS stimuli_Compare_To_Zero_out1_1;

  in4_2 <= in4_offset AFTER 2 ns;

  stimuli_Constant4_out1_1: PROCESS (rawData_in5, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      in5_offset <= holdData_in5;
    ELSE
      in5_offset <= rawData_in5;
    END IF;
  END PROCESS stimuli_Constant4_out1_1;

  in5_1 <= in5_offset AFTER 2 ns;

  stimuli_Constant5_out1_1: PROCESS (rawData_in6, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      in6_offset <= holdData_in6;
    ELSE
      in6_offset <= rawData_in6;
    END IF;
  END PROCESS stimuli_Constant5_out1_1;

  in6_1 <= in6_offset AFTER 2 ns;

  stimuli_Constant6_out1_1: PROCESS (rawData_in7, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      in7_offset <= holdData_in7;
    ELSE
      in7_offset <= rawData_in7;
    END IF;
  END PROCESS stimuli_Constant6_out1_1;

  in7_1 <= in7_offset AFTER 2 ns;

  stimuli_Constant7_out1_1: PROCESS (rawData_in8, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      in8_offset <= holdData_in8;
    ELSE
      in8_offset <= rawData_in8;
    END IF;
  END PROCESS stimuli_Constant7_out1_1;

  in8_1 <= in8_offset AFTER 2 ns;

  -- Data source for out1_expected
  out1_expected_1 <= out1_expected_table_data(to_integer(out1_addr));

  
  out1_expected_2 <= '1' WHEN out1_expected_1 /= '0' ELSE
      '0';

  out1_ref <= out1_expected_2;

  out1_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out1_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND out1 /= out1_ref THEN
        out1_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in out1: Expected " & to_hex(out1_ref) & (" Actual " & to_hex(out1))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS out1_checker;

  -- Data source for out2_expected
  out2_expected_1 <= in4_table_data_2(to_integer(out1_addr));

  
  out2_expected_2 <= '1' WHEN out2_expected_1 /= '0' ELSE
      '0';

  out2_ref <= out2_expected_2;

  out2_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out2_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND out2 /= out2_ref THEN
        out2_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in out2: Expected " & to_hex(out2_ref) & (" Actual " & to_hex(out2))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS out2_checker;

  -- Data source for out3_expected
  out3_expected_1 <= in4_table_data_4(to_integer(out1_addr));

  
  out3_expected_2 <= '1' WHEN out3_expected_1 /= '0' ELSE
      '0';

  out3_ref <= out3_expected_2;

  out3_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out3_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND out3 /= out3_ref THEN
        out3_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in out3: Expected " & to_hex(out3_ref) & (" Actual " & to_hex(out3))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS out3_checker;

  -- Data source for out4_expected
  out4_expected_1 <= out1_expected_table_data_2(to_integer(out1_addr));

  
  out4_expected_2 <= '1' WHEN out4_expected_1 /= '0' ELSE
      '0';

  out4_ref <= out4_expected_2;

  out4_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out4_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND out4 /= out4_ref THEN
        out4_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in out4: Expected " & to_hex(out4_ref) & (" Actual " & to_hex(out4))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS out4_checker;

  -- Data source for out5_expected
  out5_expected_1 <= '1';

  out5_ref <= out5_expected_1;

  out5_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out5_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND out5 /= out5_ref THEN
        out5_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in out5: Expected " & to_hex(out5_ref) & (" Actual " & to_hex(out5))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS out5_checker;

  -- Data source for out6_expected
  out6_expected_1 <= '0';

  out6_ref <= out6_expected_1;

  out6_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out6_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND out6 /= out6_ref THEN
        out6_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in out6: Expected " & to_hex(out6_ref) & (" Actual " & to_hex(out6))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS out6_checker;

  -- Data source for out7_expected
  out7_expected_1 <= '0';

  out7_ref <= out7_expected_1;

  out7_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out7_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND out7 /= out7_ref THEN
        out7_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in out7: Expected " & to_hex(out7_ref) & (" Actual " & to_hex(out7))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS out7_checker;

  -- Data source for out8_expected
  out8_expected_1 <= '1';

  out8_ref <= out8_expected_1;

  out8_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out8_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND out8 /= out8_ref THEN
        out8_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in out8: Expected " & to_hex(out8_ref) & (" Actual " & to_hex(out8))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS out8_checker;

  testFailure <= out8_testFailure OR (out7_testFailure OR (out6_testFailure OR (out5_testFailure OR (out4_testFailure OR (out3_testFailure OR (out1_testFailure OR out2_testFailure))))));

  completed_msg: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF snkDone = '1' THEN
        IF testFailure = '0' THEN
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (PASSED)**************"
            SEVERITY NOTE;
        ELSE
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (FAILED)**************"
            SEVERITY NOTE;
        END IF;
      END IF;
    END IF;
  END PROCESS completed_msg;

END rtl;

